services:
  wings:
    image: ghcr.io/pwindows/phantom-wings:latest
    restart: always
    networks:
      - wings0
    ports:
      - "8080:8080"
      - "2022:2022"
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: phantom
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/phantom/:/etc/phantom/"
      - "/var/lib/phantom/:/var/lib/phantom/"
      - "/var/log/phantom/:/var/log/phantom/"
      - "/tmp/phantom/:/tmp/phantom/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      #- "/srv/daemon-data/:/srv/daemon-data/"
      #- "/etc/letsencrypt/:/etc/letsencrypt/"

networks:
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
